### ISSUE TITLE
Arithmetic Dragons

### ISSUE THREAD

**Issue by kirbalbek** [kirbalbek/pprog_balbek#5]
@antosha417 я сделяль (до дедлайна!)

**Comment by antosha417** [comment]
http://cs.mipt.ru/python/lessons/lab3.html Прочитай ещё раз когда дедлайн

**Comment by antosha417** [comment]
Не вижу хеш коммита, не знаю что проверять и где найти твой код.

**Comment by kirbalbek** [comment]
@antosha417 
daed4c8f99076690ea2da1eaa7efb6a2ac6ff7d9
дедлайн в четверг в 23, я выложил в четверг где-то в 1:00
я мог issue сделать позже, но драконов я точно выложил до дедлайна

**Comment by antosha417** [comment]
Я вижу когда ты выложил. 
* Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
* FIXME нужно убрать, если поправил
* Добавь троллей

Пока ставлю тебе 0,8 за задачу, чтобы поднять поправь код. Умножаю на 0,7 за сдачу после дедлайна
