### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by kirbalbek** [kirbalbek/pprog_balbek#6]
@antosha417 , проверяй :)

**Comment by antosha417** [comment]
Прочитай правила игры внимательно. Не вижу хеши коммитов.

**Comment by kirbalbek** [comment]
@antosha417 
e7675031d7bf2cd13945ed6c5d3449864fd7b9c1

**Comment by antosha417** [comment]
Анимацию сдавай только после того как сдашь графику, одинаковые ошибки.

**Comment by kirbalbek** [comment]
@antosha417 
7ae8a7e8df482418b5cc7648d172ddfa6b3a26d6
исправил те же ошибки в анимации
