### ISSUE TITLE
catch balls

### ISSUE THREAD

**Issue by kirbalbek** [kirbalbek/pprog_balbek#7]
@antosha417 , проверяй

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by kirbalbek** [comment]
@antosha417 
d6735590d8c3635b424658b27da17d9b17444ab3

**Comment by antosha417** [comment]
* Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
* Глобальные переменные плохо, убери.
* Добавь документацию
* Убери ненужные импорты
* Вынеси ВЕСЬ код в функции
* Если много раз кликать на место где был шарик, то можно заработать кучу очков. Поправь

Пока ставлю тебе 0,4 за задачу, чтобы поднять поправь код.
