### ISSUE TITLE
risunok

### ISSUE THREAD

**Issue by kirbalbek** [kirbalbek/pprog_balbek#8]
@antosha417
13b23f4e09d229e8c710662b52ae37c98e62d2da

**Comment by antosha417** [comment]
* Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
* Добавь документацию
* Структурируй код так, чтобы его приятно было читать.
* Куча копипасты, надо функции
Например:
```python 
gr.Polygon
.setFill
.draw(window)
```
* Вспомни про циклы и убери копипасту

Пока ставлю тебе 0,4 за задачу, чтобы поднять поправь код.

**Comment by kirbalbek** [comment]
@antosha417 
b914a575230fb49a524a073a417e85e36be45b1b
исправил

**Comment by antosha417** [comment]
0,6
