### ISSUE TITLE
turtle

### ISSUE THREAD

**Issue by kirbalbek** [kirbalbek/pprog_balbek#9]
@antosha417
daed4c8f99076690ea2da1eaa7efb6a2ac6ff7d9

**Comment by antosha417** [comment]
Пока ставлю тебе 0 за задачу, чтобы поднять покажи код с черепахой.

**Comment by antosha417** [comment]
Наверное, не тот коммит хочешь сдать.

**Comment by kirbalbek** [comment]
@antosha417 
да, не тот коммит
c6d81cc96cd0fc4a8b2022957452945370f1f017

**Comment by antosha417** [comment]
Нет фракталов. 
Пока ставлю тебе 0,8 за задачу, чтобы поднять поправь код.
Умножаю оценку на 0,7 за сдачу после дедлайна.
